image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - cd C:/projects
  - if not exist C:/projects/vcpkg (
      git clone https://github.com/cpp-ipfs/vcpkg.git && 
      cd vcpkg && 
      .\bootstrap-vcpkg.bat)
  - cd C:/projects/vcpkg
  - .\vcpkg integrate install
  - .\vcpkg install gtest:x64-windows
  - .\vcpkg install gtest:x86-windows

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake ..

build:
  project: %APPVEYOR_BUILD_FOLDER%/ALL_BUILD.vcxproj
  verbosity: minimal

test_script:
  - ctest -C %CONFIGURATION%

cache:
  - C:/projects/vcpkg
